import { Clapperboard, Globe2, MessageCircle, Share2 } from "lucide-react";
import { Link } from "react-router-dom";

function Footer() {
  const year = new Date().getFullYear();

  return <footer className="mt-16 border-t border-white/[0.08] bg-[#0b0b10]"><div className="mx-auto grid max-w-[1600px] gap-9 px-5 py-9 sm:grid-cols-2 sm:px-8 lg:grid-cols-[1.6fr_1fr_1fr] lg:px-12"><div><Link to="/" className="flex items-center gap-2 font-display text-sm font-medium text-zinc-200"><Clapperboard size={17} className="text-amber" /> NFAK Recommendation Engine</Link><p className="mt-3 max-w-sm text-[13px] leading-5 text-zinc-600">Discover films that match your taste, from the stories trending close to home to favourites from around the world.</p><div className="mt-4 flex gap-3"><a href="#community" aria-label="Community" className="text-zinc-600 transition hover:text-amber"><Globe2 size={15} /></a><a href="#messages" aria-label="Messages" className="text-zinc-600 transition hover:text-amber"><MessageCircle size={15} /></a><a href="#share" aria-label="Share" className="text-zinc-600 transition hover:text-amber"><Share2 size={15} /></a></div></div><div><h2 className="text-[10px] font-medium uppercase tracking-[0.18em] text-zinc-400">Explore</h2><div className="mt-3 grid gap-2 text-[13px] text-zinc-600"><Link to="/about" className="transition hover:text-amber">About Us</Link><Link to="/contact" className="transition hover:text-amber">Contact Us</Link></div></div><div><h2 className="text-[10px] font-medium uppercase tracking-[0.18em] text-zinc-400">Legal</h2><div className="mt-3 grid gap-2 text-[13px] text-zinc-600"><Link to="/terms" className="transition hover:text-amber">Terms &amp; Conditions</Link><Link to="/privacy" className="transition hover:text-amber">Privacy Policy</Link></div></div></div><div className="border-t border-white/[0.06]"><p className="mx-auto max-w-[1600px] px-5 py-4 text-[11px] tracking-wide text-zinc-700 sm:px-8 lg:px-12">© {year} NFAK Recommendation Engine. Educational project.</p></div></footer>;
}

export default Footer;
